name: Lambda Deploy
on:
  push:
    branches:
      - master
jobs:
  get-filenames:
    runs-on: ubuntu-latest
    outputs:
      lambdaArray: ${{ steps.getLambdas.outputs.lambdas }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get functions filenames
        id: getLambdas
        run: |
          cd functions
          lambdas=$(tree -d -L 1 -J . | jq -j -c '.[0].contents | map(.name)')
          echo ::set-output name=lambdas::${lambdas}
  update-code:
    needs: get-filenames
    strategy:
      matrix:
        lambda: ${{ fromJSON(needs.get-filenames.outputs.lambdaArray) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Zip Lambda functions
        run: zip -j ${{matrix.lambda}}.zip ./functions/${{matrix.lambda}}/${{matrix.lambda}}.py
      - name: Create or Update Lambda
        run: |
          if aws lambda get-function --function-name=${{matrix.lambda}}; then
            echo "Lambda exists - changing handler"
            aws lambda update-function-configuration --function-name=${{matrix.lambda}} --handler=${{matrix.lambda}}.lambda_handler
            aws lambda update-function-code --function-name=${{matrix.lambda}} --zip-file=fileb://${{matrix.lambda}}.zip
          else
            echo "Creating lambda"
            aws lambda create-function --function-name={{matrix.lambda}} --role arn:aws:iam::992382430749:role/s3-full-access --zip-file=fileb://${{matrix.lambda}}.zip
            aws lambda update-function-configuration --function-name=${{matrix.lambda}} --handler=${{matrix.lambda}}.lambda_handler
          fi